name: Unit Testing and Code Formatting

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: "test"
      KEY_DELIVERY_API_KEY: ${{ secrets.KEY_DELIVERY_API_KEY }}
      KEY_DELIVERY_API_SECRET: ${{ secrets.KEY_DELIVERY_API_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Check code formatting
        run: ./gradlew spotlessCheck --no-daemon
      - name: Build with Gradle
        run: ./gradlew -x spotlessCheck build --no-daemon